plugin: aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Owner: "Alejandro Martinez"

hostnames:
  - private-ip-address
  - instance-id
keyed_groups:
  - key: tags.role
    prefix: role
compose:
  ansible_host: public_ip_address
