name: CI - Validation

on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible==9.3.0 ansible-lint boto3 botocore

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform FMT Check
        run: terraform -chdir=terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Run ansible-lint
        run: ansible-lint ansible/

      - name: Run security scan (Checkov)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
